### ISSUE TITLE
Dont sleep during download update

### ISSUE THREAD

**Issue by carcaschoi** [D3fau4/NightFall#20]
Would you like to block sleep mode during download update？

**Comment by D3fau4** [comment]
Do you think it would be better to add it as an option or force the user?

**Comment by carcaschoi** [comment]
I think it is better to force

**Comment by D3fau4** [comment]
okey

**Comment by carcaschoi** [comment]
not only block the power button but also block automatically sleep

**Comment by carcaschoi** [comment]
thx D3fau4, look forward to your next update😁👍
